apiVersion: apps/v1
kind: Deployment
metadata:
  name:  usermgmt2
  namespace: onlineordermanagement
  labels:
    app:  usermgmt2
spec:
  selector:
    matchLabels:
      app: usermgmt2
  replicas: 1
  template:
    metadata:
      labels:
        app:  usermgmt2
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  usermgmt2
        image:  rithuikyerrabrolu/usermgmt:v1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          value: Testing
        ports:
        - containerPort:  8080
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always